### ISSUE TITLE
Volume server loses connection with master server

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/weed-fs#100]
Our weed master log contains a lot of followign messages:
>I0309 07:24:05 02801 topology_event_handling.go:39] DataNode 10.1.3.131:8071 is dead!
>I0309 07:24:48 02801 node.go:208] topo:InforelayLA:rack1 adds child 10.1.3.131:8071

Why weed volume server loses connection with master? Can we increase timeouts/increase ping requests count?

**Comment by chrislusf** [comment]
You can increase the "-pulseSeconds" on master from default 5 seconds to some higher number.

**Comment by fedotxxl** [comment]
thanks. Can you add this info to docs?

**Comment by chrislusf** [comment]
added to FAQ page. https://github.com/chrislusf/weed-fs/wiki/FAQ

**Comment by ingardm** [comment]
Did anyone come up with a sensible number for this?

**Comment by chengsu** [comment]
Is there any play to add auto reconnectting?
