### ISSUE TITLE
please change directories to point github when available;

### ISSUE THREAD

**Issue by faaliyet** [chrislusf/weed-fs#106]
I had problem while trying to install from the source; the problem was, it didn't download all the sources , because the website of bazil.org source was down.

imports github.com/bazillion/fuse
is it not better?

Website is offline
No cached version of this page is available.

You
Browser
Working
Prague
CloudFlare
Working
bazil.org
Host
Error 

[root@seaweedfs seaweedfs]# go get github.com/chrislusf/weed-fs/go/weed
package github.com/chrislusf/weed-fs/go/weed
	imports bazil.org/fuse: unrecognized import path "bazil.org/fuse"
package github.com/chrislusf/weed-fs/go/weed
	imports bazil.org/fuse/fs: unrecognized import path "bazil.org/fuse/fs"
package github.com/chrislusf/weed-fs/go/weed
	imports github.com/dgrijalva/jwt-go
	imports github.com/gocql/gocql
	imports code.google.com/p/snappy-go/snappy
	imports github.com/golang/groupcache/lru
	imports speter.net/go/exp/math/dec/inf
	imports github.com/golang/protobuf/proto
	imports github.com/syndtr/goleveldb/leveldb
	imports github.com/syndtr/goleveldb/leveldb/util
	imports github.com/syndtr/gosnappy/snappy
	imports gopkg.in/redis.v2: unrecognized import path "gopkg.in/redis.v2"
[root@seaweedfs seaweedfs]# go get github.com/chrislusf/weed-fs/go/weed
package bazil.org/fuse: unrecognized import path "bazil.org/fuse"
package bazil.org/fuse/fs: unrecognized import path "bazil.org/fuse/fs"
[root@seaweedfs seaweedfs]# go get github.com/chrislusf/weed-fs/go/weed
package bazil.org/fuse: unrecognized import path "bazil.org/fuse"
package bazil.org/fuse/fs: unrecognized import path "bazil.org/fuse/fs"
[root@seaweedfs seaweedfs]# go get github.com/chrislusf/weed-fs/go/weed
package bazil.org/fuse: unrecognized import path "bazil.org/fuse"
package bazil.org/fuse/fs: unrecognized import path "bazil.org/fuse/fs"
[root@seaweedfs seaweedfs]# go get github.com/chrislusf/weed-fs/go/weed
package bazil.org/fuse: unrecognized import path "bazil.org/fuse"
^C[root@seaweedfs seaweedfs]# go get github.com/chrislusf/weed-fs/go/weed
package bazil.org/fuse: unrecognized import path "bazil.org/fuse"
package bazil.org/fuse/fs: unrecognized import path "bazil.org/fuse/fs"
[root@seaweedfs seaweedfs]# go get github.com/chrislusf/weed-fs/go/weed
package bazil.org/fuse: unrecognized import path "bazil.org/fuse"

**Comment by chrislusf** [comment]
This needs to ask the fuse authors.

**Comment by faaliyet** [comment]
alright.
