### ISSUE TITLE
is it, how it works? multiple failures and then detects the master;

### ISSUE THREAD

**Issue by faaliyet** [chrislusf/weed-fs#107]
I don't remember something like this; in v0.68. So, I'm not sure if this is how it's supposed to be. 
./weed master -mdir="/storage/seaweedfs/meta/" -port=9333 -volumeSizeLimitMB=10000 &
./weed volume -dir="/storage/seaweedfs/vol_1/" -max=1 -mserver="0.0.0.0:9333" -port=7001 -images.fix.orientation=false

also tried with -mserver="localhost:9333" before 0.0.0.0:9333.

I0329 15:16:47 20789 master.go:70] Start Seaweed Master 0.69 beta20150226 at 0.0.0.0:9333
I0329 15:16:47 20790 file_util.go:20] Folder /storage/seaweedfs/vol_1/ Permission: -rwxrwxr-x
I0329 15:16:47 20790 store.go:220] Store started on dir: /storage/seaweedfs/vol_1/ with 0 volumes max 1
I0329 15:16:47 20790 volume.go:128] Start Seaweed volume server 0.69 beta20150226 at 0.0.0.0:7001
I0329 15:16:47 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:16:47 20789 raft_server.go:103] Old conf,log,snapshot should have been removed.
I0329 15:16:48 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:16:49 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:16:51 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:16:52 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:16:53 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:16:54 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:16:56 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:16:57 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:16:58 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:16:59 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:17:01 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:17:02 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:17:03 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:17:04 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:17:06 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:17:07 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:17:08 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:17:09 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:17:11 20790 volume_server.go:80] Volume Server Failed to talk with master &{0.0.0.0:9333 {{%!s(int32=0) %!s(uint32=0)} %!s(uint32=0) %!s(uint32=0) %!s(int32=0) %!s(int32=0)} %!s(int=5)   %!s(*storage.Store=&{127.0.0.1 7001 127.0.0.1:7001 [0xc20803a120]   false 0 0xc20803a720}) %!s(*security.Guard=&{[]  false}) %!s(bool=false) %!s(bool=false)}: No master node available!
I0329 15:17:11 20789 master_server.go:89] [ localhost:9333 ] localhost:9333 becomes leader.
I0329 15:17:12 20789 node.go:208] topo adds child DefaultDataCenter
I0329 15:17:12 20789 node.go:208] topo:DefaultDataCenter adds child DefaultRack
I0329 15:17:12 20789 node.go:208] topo:DefaultDataCenter:DefaultRack adds child 127.0.0.1:7001
I0329 15:17:12 20790 volume_server.go:77] Volume Server Connected with master at localhost:9333

**Comment by chrislusf** [comment]
That's ok. Just some extra logging.
