### ISSUE TITLE
assign?count=0 leads to unexpected behaviour

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/weed-fs#109]
Problem:
`assign?count=0` returns ID X and file is correctly uploaded by this ID. If I upload few more files to same volume file with ID X will be not accessible (404).

Steps to reproduce:
1. Get ID with `assign?count=0` and remember it. Upload file by this ID. 
2. Repeat `1` several times until you will upload few more files to the same volume several times
3. Check file with remembered id. It should be not accessible

How to fix:
Skip `count` param

Suggestion:
If `count <= 0` is not expected could you raise an exception? 

Weed version: `0.65`

**Comment by chrislusf** [comment]
Added fix on git HEAD.
