### ISSUE TITLE
Strange GZIP bahviour

### ISSUE THREAD

**Issue by vitalybaev** [chrislusf/weed-fs#112]
Example URL: http://st.sprashivai.net/10/081330ecc8/secure.min.js
This is js file, that must be gzipped, but: 

1) In Chrome it works well
![2015-04-09 14 53 22](https://cloud.githubusercontent.com/assets/724423/7066135/34b62760-dec8-11e4-8ddc-ad102156011e.png)
2) But in Safari, and via some online tools (http://checkgzipcompression.com/) GZIP don't work.
![2015-04-09 14 54 15](https://cloud.githubusercontent.com/assets/724423/7066151/5d0c0dc4-dec8-11e4-8f63-bc71e9cba219.png)
We use latest weed, compiled with go 1.4

**Comment by chrislusf** [comment]
Sending gzip content back to clients is conditionally turned on here:
https://github.com/chrislusf/weed-fs/blob/master/go/weed/weed_server/volume_server_handlers_read.go#L103

Maybe you can print out debug message to find out?

**Comment by vitalybaev** [comment]
I've see debug info, the reason is IzGzipped function return false in my case

https://github.com/chrislusf/weed-fs/blob/master/go/weed/weed_server/volume_server_handlers_read.go#L102

**Comment by vitalybaev** [comment]
Sorry, I've checking debug output and realize, that file was uploaded via weed php library WITHOUT filename - so, weed didn't match gzip criteria, and didn't gzipped it.
