### ISSUE TITLE
publicUrl not support ssl(https)

### ISSUE THREAD

**Issue by hetao29** [chrislusf/weed-fs#117]
if I start the weed volume like this, (don't worry the ssl keys, I user nginx proxy):
```
weed -log_dir=/data/weed/logs/ -v=2 volume -ip="devf3.xxx.com" -publicUrl="https://devf3.xxx.com" -dir=/data/weed/data_test/volume3 -port=8083 -mserver="devm1.xxx.com:9333" &
```
and the img url will be:
```
http://https//devf2.xxxx.com/1,014a610fdcd1 
```

**Comment by chrislusf** [comment]
Will fix this.

**Comment by hetao29** [comment]
thanks very much~~

何涛 Hetal

Tel: 13488810858

北京市海淀区，100080




2015-04-16 15:12 GMT+08:00 chrislusf <notifications@github.com>:

**Comment by chrislusf** [comment]
I add the fix. It will check the url before http redirect. If it already has "http" prefix, it will stop auto prepend a "http://" prefix.

Is that your use case?

**Comment by hetao29** [comment]
yes, that's my want. thanks very much~

何涛 Hetal

Tel: 13488810858

北京市海淀区，100080




2015-04-17 1:05 GMT+08:00 chrislusf <notifications@github.com>:
