### ISSUE TITLE
Missing build instructions for Mac OSX 10.9.4

### ISSUE THREAD

**Issue by evandrix** [chrislusf/weed-fs#13]
I can't find the precompiled binary release for my OS platform (Mac OSX 10.9.4) on your linked page.

When I `git clone` this repo, I find a bunch of *.go files in some subfolders. Is there a Makefile to compile all of these into a `weed` binary myself?

**Comment by linxiaobai** [comment]
https://github.com/chrislusf/seaweedfs/releases
darwin_amd64.tar.gz
