### ISSUE TITLE
expose http GET only

### ISSUE THREAD

**Issue by devinrsmith** [chrislusf/weed-fs#14]
Is there currently a way to expose the GET resource separately from the other GETs & POSTs?

ie:

I would like to (publicly) provide access to

```
GET http://server1.example.com:8080/3,238ceaa9a7
```

but not to

```
POST http://server1.example.com:8080/3,238ceaa9a7
```

nor 

```
GET http://server1.example.com:8080/status (etc...)
```

Right now my alternatives seem to be:
* iptable string matching (which doesn't seem very fun)
* proxy server (extra hop + defeats the purpose of fully concurrent reads)

I think a reasonable solution would be to provide some alternative ip:port binding for just the resource GETs.

**Comment by chrislusf** [comment]
Here are some design thoughts. https://groups.google.com/forum/#!topic/weed-file-system/MHumA5d-Zw0

Please add your ideas.

**Comment by chrislusf** [comment]
Simplifying the design by adding a "-port.public" option (in v0.69beta as of now). If set, the public port will only serve GET or HEAD requests. The JWT feature can be done later.
