### ISSUE TITLE
content type from volume post upload always text/plain?

### ISSUE THREAD

**Issue by devinrsmith** [chrislusf/weed-fs#16]
I'm assuming the return content-type should be application/json?

```
$ curl -v -F "file=@/tmp/test.json;type=application/json" localhost:8080/7,07a27ee211
> POST /7,07a27ee211 HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:8080
> Accept: */*
> Content-Length: 223
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=----------------------------2f1cf300fd2b
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 201 Created
< Date: Mon, 29 Sep 2014 20:08:45 GMT
< Content-Length: 30
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
{"name":"test.json","size":74}
```

**Comment by kyzer028** [comment]
I Chris, I faced the same problem, and I have been able to fix this in a dirty way, but I think it needs some refacto...

Regarding golang documentation : [http://golang.org/pkg/net/http/#Header.Write](http://golang.org/pkg/net/http/#Header.Write)
It says : "Changing the header after a call to WriteHeader (or Write) has no effect."

In `go/weed/weed_server/volume_server_handlers.go` you call `w.writeHeader(http.StatusCreated)` first and after in `common.go` writeJson method you set the content-type to json but it has no-effect...

If you do the following in `go/weed/weed_server/volume_server_handlers.go` it will work with json content-type

```
	if errorStatus == "" {
	 +	w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(http.StatusCreated)
	} else {
		w.WriteHeader(http.StatusInternalServerError)
```

Hope this helps

**Comment by chrislusf** [comment]
@kyzer028 Thanks a lot!!!!!

I took the time to fix similar problems everywhere.

commit 5b5d6341e570b2f12cd375279ee004529193b970
Author: Chris Lu <chris.lu@gmail.com>
Date:   Thu Jan 8 00:19:32 2015 -0800

    Set http status after modifying response headers.

**Comment by kyzer028** [comment]
@chrislusf You're welcome, thanks for fixing it that quickly :+1:
