### ISSUE TITLE
Stability of master servers

### ISSUE THREAD

**Issue by ernado** [chrislusf/weed-fs#17]
I'm using weed-fs in production now. Sometimes master server randomly respond with blank line or "no more volumes" error. (even when correct topology in /dir/status) 
I used 3 master-servers and it caused to even decrease overall stability of the system - sometimes master servers lost sync with each other / unable to promote the leader, and the only way fixing it was removing all master server files, shutting down all master servers and data nodes, then starting master servers and nodes.

I'm not quite sure how to investigate this problem, because reproducibility is low - I have no idea how to force master server(s) into unavailable state.  

Maybe some hardcore unit/integration tests?
This issue not allowing me to use weed-fs in production for my new projects and I'm currently migrating to cloud storage, but leaving possibility for migrating back.

**Comment by chrislusf** [comment]
Closing because there are no particular actions on this.
