### ISSUE TITLE
Need help: Unable to upload files/objects to local Seaweed AWS S3 server

### ISSUE THREAD

**Issue by cskru** [chrislusf/weed-fs#3018]
### Discussed in https://github.com/chrislusf/seaweedfs/discussions/3017

<div type='discussions-op-text'>

<sup>Originally posted by **cskru** May  6, 2022</sup>
**Environement details:**
**aws cli version:** aws-cli/1.23.8 Python/3.6.0 Windows/10 botocore/1.25.8
**Seaweed installer that I've used:** https://github.com/chrislusf/seaweedfs/releases/download/3.01/windows_amd64.zip

**Clients I have tried**
AWS Java SDK 2
AWS Java SDK 1
aws cli version 1 
aws cli version 2

Getting same error.

===========================

I have started the server using
`weed server -s3`

I set the configurations this way:
```
> s3.configure -access_key=test -secret_key=test -user=admin -actions=Read,Write,List,Tagging,Admin -apply
{
  "identities": [
    {
      "name": "admin",
      "credentials": [
        {
          "accessKey": "test",
          "secretKey": "test"
        }
      ],
      "actions": [
        "Read",
        "Write",
        "List",
        "Tagging",
        "Admin"
      ]
    }
  ]
}
```

I also tried to initialize the server with same static configuration.

**All bucket operations go through. make bucket, list, remove, get, etc..**

But, uploading a file to S3 is not going through.

```
> aws --endpoint-url http://localhost:8333 s3 cp sample.txt s3://newbucket
```
```
upload failed: .\sample.txt to s3://newbucket/sample.txt An error occurred (InternalError) when calling the PutObject operation (reached max retries: 4): We encountered an internal error, please try again.
```

Before setting up the above authentication, when I tried to upload file like I've explained above, I got an error that asked me to setup authentication or Seaweedfs S3.
Hence, I followed the wiki to setup auth like I've explained above.

.aws/credentials are properly set and the corresponding env variables are also perfect.
Which is why **I am able to perform all operations on bucket like make, remove, list, etc.**

## Any help is very much appreciated</div>

**Comment by chrislusf** [comment]
there are no version info or logs.

Possibly the same issue as https://github.com/chrislusf/seaweedfs/issues/3013

Please use the dev version https://github.com/chrislusf/seaweedfs/releases/tag/dev
or wait for the next release this Sunday.

**Comment by cskru** [comment]
@chrislusf , thank you for the timely response.  

The logs on seaweed server are same as #3013 : dial unix: missing address
On the client it's 500 Internal server error.

I get same message on the server even when I make bucket as well, but that goes through.
Only file related operations are giving 500 (as seen on Java SDK and AWS CLI).

I'll try dev version as you've suggested.

**Comment by cskru** [comment]
@chrislusf 
File upload, download etc is now working with dev exe: https://github.com/chrislusf/seaweedfs/releases/download/dev/weed-20220509-0529-windows-amd64.zip

Thanks for the suggestion.

**Comment by cskru** [comment]
@chrislusf , now with the dev exe (https://github.com/chrislusf/seaweedfs/releases/download/dev/weed-20220509-0529-windows-amd64.zip) I am facing another issue with presigned urls.

Explanation:
Create an upload presign url - Works
If I try to do a PUT, for the same url, I get the below error:
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
    <Resource>/newbucket/sample.txt</Resource>
    <RequestId>1652075615580054400</RequestId>
    <Key>sample.txt</Key>
    <BucketName>newbucket</BucketName>
</Error>

=============

Tried to generate presigned URL via aws cli, Java SDK 2.
Both give same error.

But If I try to do a GET on presigned URL, that works.

I have also set the signature version, as mentioned in the Seaweed wiki: (https://github.com/chrislusf/seaweedfs/wiki/AWS-CLI-with-SeaweedFS#configuration)
```
$ aws configure set default.s3.signature_version s3v4
```

**Comment by chrislusf** [comment]
Need to make it reproducible.

**Comment by chrislusf** [comment]
please create a separate issue with reproducing steps/code.
