### ISSUE TITLE
The replication in weed is Strong consistency?

### ISSUE THREAD

**Issue by aszxqw** [chrislusf/weed-fs#47]
I saw the codes in `ReplicatedWrite` (store_replicate.go) ,
When the file uploaded, `ReplicatedWrite` will do replication (to another volume server) first, and when the replication is done, return the result , so I think The replication in weed is Strong consistency , is it right?

**Comment by chrislusf** [comment]
Yes. The write is success if and only if all the copies are successfully written.

**Comment by aszxqw** [comment]
Thanks!
