### ISSUE TITLE
Some dep package path needs to update

### ISSUE THREAD

**Issue by yourchanges** [chrislusf/weed-fs#55]
* The https://code.google.com/p/gogoprotobuf/ has be moved to the https://github.com/gogo/protobuf
* The https://code.google.com/p/goprotobuf has be moved to the https://github.com/golang/protobuf

And other suggestions:

* The https://speter.net/go/exp/math/dec/inf and https://code.google.com/p/snappy-go/snappy should be placed in weedfs like glog package

**Comment by chrislusf** [comment]
Is it possible to fix it and send a pull request? I could not locate any package you mentioned or the package is already updated.

**Comment by yourchanges** [comment]
For example, the https://github.com/golang/protobuf just be updated 9 hours ago.

And the pull request need some time to prepare and test

**Comment by chrislusf** [comment]
Current file is already using github.com/golang/protobuf

Is it broken now?

**Comment by yourchanges** [comment]
Yes, you are right, but it's wired, may be there is a nested deps. when I DO go get, it outs:

yourchangesMac:developer yourchanges$ go get -v  github.com/chrislusf/weed-fs/go/weed
bazil.org/fuse
github.com/chrislusf/weed-fs/go/glog
github.com/chrislusf/weed-fs/go/stats
github.com/golang/protobuf/proto
golang.org/x/image/bmp
golang.org/x/image/tiff/lzw
github.com/rwcarlsen/goexif/tiff
github.com/tgulacsi/go-cdb
code.google.com/p/snappy-go/snappy
golang.org/x/image/tiff
github.com/golang/groupcache/lru
speter.net/go/exp/math/dec/inf
github.com/syndtr/goleveldb/leveldb/util
github.com/chrislusf/weed-fs/go/util
github.com/rwcarlsen/goexif/exif
github.com/syndtr/goleveldb/leveldb/comparer
github.com/gocql/gocql
github.com/syndtr/goleveldb/leveldb/cache
github.com/syndtr/goleveldb/leveldb/storage
github.com/disintegration/imaging
github.com/syndtr/goleveldb/leveldb/filter
github.com/chrislusf/weed-fs/go/filer
github.com/syndtr/gosnappy/snappy
github.com/syndtr/goleveldb/leveldb/opt
github.com/chrislusf/weed-fs/go/filer/flat_namespace
gopkg.in/bufio.v1
github.com/dgrijalva/jwt-go
github.com/chrislusf/weed-fs/go/sequence
code.google.com/p/gogoprotobuf/proto
bazil.org/fuse/fuseutil
bazil.org/fuse/fs
github.com/syndtr/goleveldb/leveldb/errors
github.com/syndtr/goleveldb/leveldb/iterator
github.com/syndtr/goleveldb/leveldb/journal
github.com/chrislusf/weed-fs/go/images
gopkg.in/redis.v2
github.com/chrislusf/weed-fs/go/security
code.google.com/p/goprotobuf/proto
github.com/syndtr/goleveldb/leveldb/memdb
github.com/syndtr/goleveldb/leveldb/table
github.com/gorilla/context
github.com/gorilla/mux
github.com/chrislusf/weed-fs/go/operation
github.com/syndtr/goleveldb/leveldb
github.com/chrislusf/weed-fs/go/filer/cassandra_store
github.com/chrislusf/weed-fs/go/storage
github.com/goraft/raft/protobuf
github.com/goraft/raft
github.com/chrislusf/weed-fs/go/filer/redis_store
github.com/chrislusf/weed-fs/go/filer/embedded_filer
github.com/chrislusf/weed-fs/go/topology
github.com/chrislusf/weed-fs/go/weed/weed_server
github.com/chrislusf/weed-fs/go/weed

**Comment by chrislusf** [comment]
Most of the related usages come from github.com/syndtr/goleveldb
