### ISSUE TITLE
Restoring from idx and dat only?

### ISSUE THREAD

**Issue by devinrsmith** [chrislusf/weed-fs#57]
I'm migrating volumes from one machine to another.

It seems like volumes start up fine with only idx and dat files. (I see the volumes being loaded in the logs.)

When the volumes are connected to a fresh master and I do /dir/assign, the master grows new volumes instead of allocating into the existing volumes. Is this expected behavior?

**Comment by chrislusf** [comment]
Only the idx and dat files are needed. (btw: actually the idx files can be re-generated from dat files also.)

The master should accept the migrated volumes as writable (for replicated volumes only if the replication copies are all live).

Check http://master:port/dir/status?pretty=y to see which volumes are writable.

**Comment by devinrsmith** [comment]
Turned out it was queried with a different replication. Thanks.
