### ISSUE TITLE
Reading Multi part error

### ISSUE THREAD

**Issue by devinrsmith** [chrislusf/weed-fs#59]
Getting tons of these errors, unable to upload. Any ideas? Restarted the volume and things are working now. 

`I0115 15:02:57 00001 needle.go:65] Reading Multi part [ERROR] EOF`

(Edit: restarting didn't fix things)

**Comment by devinrsmith** [comment]
This may be b/c my master and volumes where different versions... updating to latest will update soon.

**Comment by devinrsmith** [comment]
Updated everything to 0.68 still has issues, going back to 0.67.

**Comment by chrislusf** [comment]
There is a very recent change on parsing multipart uploads.

**Comment by chrislusf** [comment]
Related to this? https://github.com/chrislusf/weed-fs/pull/56

**Comment by devinrsmith** [comment]
Back to 0.67, things working again.

**Comment by yourchanges** [comment]
@devinrsmith  Could you PLEASE give the request payload or the example to show how the multipart uploads failed?

**Comment by yourchanges** [comment]
@devinrsmith by the way,  the tons of the error logs is needed too. 

And our product env run the master bench very well without any issues.

**Comment by devinrsmith** [comment]
I've rolled back to 0.67 for the time, but I'll see if I can't get a dump of what was sent over the wire later. It should be a pretty standard post I think. I don't think the error logs will help too much as it's just the same thing repeated over and over. 

https://gist.github.com/devinrsmith/a55b55e2ac12d50c4559

**Comment by yourchanges** [comment]
There is a way to cause into "dead-for" loop, the request payload didn't have a 'filename' properties in dispositionParams parsed from the Content-Disposition. 

for example:

------------gL6KM7cH2ae0Ij5ae0KM7ae0ae0gL6
Content-Disposition: form-data; name="file"; <filename="IMG_1840.JPG" ---miss >
Content-Type: application/octet-stream

@devinrsmith could you give the some client javascript code(or the command line) to show how to submit the form

**Comment by chrislusf** [comment]
Right. Previous version allows empty file names.

**Comment by yourchanges** [comment]
@chrislusf but it seems be not RFC(https://www.ietf.org/rfc/rfc2388.txt 4.4) valid if the filename is empty, in the java world "commons-upload.jar"  also  check the filename to judge a multi-part item DO a file item

**Comment by chrislusf** [comment]
The previous version supports bare blob. This is because weedfs is more a key~blob store, not necessarily a file with filename.

I suggest we still support uploads with empty filename.

**Comment by devinrsmith** [comment]
Yep, this must be it. I'm not setting filename.

**Comment by yourchanges** [comment]
But I think the weedfs is HTTP file server too, it runs well, and it should handle these client such as jquery uploadify tools request.

**Comment by chrislusf** [comment]
Not saying we should not support other tools. But we still can support empty file names.

**Comment by yourchanges** [comment]
@chrislusf  the improved code: needle.go L64-L84:

        part, fe := form.NextPart()
	for {
		if fe != nil {
			glog.V(0).Infoln("Reading Multi part [ERROR]", fe)
			e = fe
			return
		}

		if part.FileName() != "" {
			break //found the first <file type> multi-part
		}

		part2, fe := form.NextPart()

		//no more multi-part items, we take the last multi-part item as the target
		if fe == io.EOF {
			break
		} else {
			part = part2
		}
	}

**Comment by chrislusf** [comment]
Haven't tested it but looks good. Send a pull request please.

**Comment by yourchanges** [comment]
ok, I'll do it later, it's 03:14 am, 16 Jan in China, I'm going to sleep now.

**Comment by chrislusf** [comment]
@devinrsmith Maybe you can confirm the fix?

**Comment by devinrsmith** [comment]
Has a binary been compiled? I can check it out tomorrow.

**Comment by chrislusf** [comment]
No compiled binary published yet. But I can send you the binary if you need it. Closing this. My local test seems good.
