### ISSUE TITLE
image id format change?

### ISSUE THREAD

**Issue by devinrsmith** [chrislusf/weed-fs#61]
It seems like image ids have dramatically increased in size (I'm assuming since I've updated versions)... is this expected?

old style: 4,92569a439e91
new style: 4,fee4fdc8838a1ec4f305f7fe

**Comment by chrislusf** [comment]
No id format change recently. 

Your file id has a pretty big file key fee4fdc88a1ec4. I suspect one of the volume had some write errors.

The complicated part is that the file key is a global sequence. So if one of the volume has a wrong format with a strangely large number, the number will be the max of the sequence and all the following generated ids are based on the large number.

This will not cause any read write errors though. The system should still work fine.

**Comment by devinrsmith** [comment]
Doesn't seem comforting knowing that there are write errors... one of my volumes was also recently throwing errors and I did "fix" to fix the index. Are these bugs in the code?

**Comment by chrislusf** [comment]
seems related to #87
