### ISSUE TITLE
Seems like "-log_dir" not parsed

### ISSUE THREAD

**Issue by thejae** [chrislusf/weed-fs#63]
OS: Ubuntu 14.04.1 LTS
Weed version: 0.68 (downloaded from pre-compiled deb package)

Run Command:
```bash
/usr/bin/weed -log_dir="/var/log/weed" -alsologtostderr=false -v=4 master -mdir="/tmp" -port=9333 -volumeSizeLimitMB=30000 -ip="10.130.197.44"
```
Viewing Log Command:
```bash
root@static:/var/log# tail /var/log/weed
tail: cannot open ‘/var/log/weed’ for reading: No such file or directory
```

**Comment by chrislusf** [comment]
This behavior comes from glog. It does not create the folder automatically.

**Comment by thejae** [comment]
Folder exists and I even created the 'weed' file to make sure.

**Comment by thejae** [comment]
@chrislusf Any suggestion there? Thanks!

**Comment by chrislusf** [comment]
show me "ls -al /var/log/weed"

**Comment by chrislusf** [comment]
"/var/log/weed" should be a writable folder, not a file.
