### ISSUE TITLE
Wrong HTTP verb semantics around file creation

### ISSUE THREAD

**Issue by stuartpb** [chrislusf/weed-fs#65]
According to [the README](https://github.com/chrislusf/weed-fs#write-file), the /assign request is a "GET", but performing this "GET" *creates* a space for a file. HTTP GET actions are supposed to only be used for actions that *do not modify state* (ie. they can be cached, and a spider re-requesting them thousands of times a second won't have any effect other than a transient increase in server load).

The /assign request should be a POST, as it *creates* something. This avoids intermediate components breaking things by making assumptions about the behavior of GET requests (ie. a caching layer not forwarding the GET request to the server).

(Reading [the further API documentation](https://github.com/chrislusf/weed-fs/blob/master/docs/api.rst), this also applies to `/vol/vacuum`, `/vol/grow`, and `/admin/assign_volume`. GET is an appropriate verb for `/dir/lookup`, `/cluster/status`, `/dir/status`, and `/status`.)

Similarly, the requests to upload file content are "POST" requests, but they should be "PUT" requests, as they are replayable to *restore* state.

**Comment by chrislusf** [comment]
Very good point!

Actually the HTTP APIs, e.g., /dir/assign,  supports all GET/POST/PUT. And the uploads support both POST and PUT.

It's hard to break current behavior though.

**Comment by stuartpb** [comment]
> Very good point!
>
> Actually the HTTP APIs, e.g., /dir/assign,  supports all GET/POST/PUT. And
> the uploads support both POST and PUT.

Well, if it's *possible* to use the correct verbs, that's good enough for
me - I'll put a pull request in later for tweaking the examples in the
documentation.
