### ISSUE TITLE
I think weed-fs needs a web console

### ISSUE THREAD

**Issue by yanyiwu** [chrislusf/weed-fs#67]
For ops can see the weed-fs running information or some helpful command. 

For example, yesterday I met a problem about two master server both thinking itself is the leader,
so that clients can not upload any file (by `/submit` ) .
And if it has a web console, anyone can easily look up the cluster information any time to find out the problem.

In the end, we restarted the two master server to solve this problem.

**Comment by yourchanges** [comment]
+1

**Comment by shel3over** [comment]
agree :+1: 
but this is another project

**Comment by aszxqw** [comment]
@shel3over  In my opinion , In the same project would be better.

**Comment by chrislusf** [comment]
We can start by designing here first.

I has half-baked web UI, which is GWT based and talk with master and volume servers via JSON. But it seems too much effort is needed. I do not want to continue down this route.

One thing I noticed is that the UI would need many more data. So I expect many server side changes also.

**Comment by shel3over** [comment]
@chrislusf  ruby/python Web UI is better / rapid  development

**Comment by aszxqw** [comment]
If you really like to use a web frame, maybe `beego` is a good choice.

**Comment by chrislusf** [comment]
If anyone can develop some prototype with good UI, I can help to maintain it.

**Comment by h-sen-dev** [comment]
dislike about non-golang web frameworks. I suggest beego.

**Comment by chrislusf** [comment]
Actually, let's not design this as a comminity. I need a volunteer build a prototype with whatever technology. I believe the volunteer will have sane judgement on tech stack choices.

**Comment by chrislusf** [comment]
Added initial UI in git HEAD.
