### ISSUE TITLE
Is the `-mdir` of weed master server irrelevant with volume server ?

### ISSUE THREAD

**Issue by aszxqw** [chrislusf/weed-fs#68]
If I rm the `mdir` , and restart the master servers , any bad things will happend?

**Comment by chrislusf** [comment]
It's a place to store meta data. "-mdir" defaults to a tmp directory. Meta data includes, "last seen max file key", "last seen max volume id", weed master cluster information.

"cluster information" is provided via command line, and the 2 "last seen max" numbers are provided through volume servers. So if removing the mdir, no bad things will happen.

**Comment by aszxqw** [comment]
ok.
And by the way,
I think document should point out clearly that `weed server ...` is a bad usage!
If a cluster contains multi `weed server` , because  the raft  is unstable when network going wrong and the cluster will refuse uploading files.
In that case, we can restart them( weed server) to solve problem, but at that time when restarting , not any file can be writed or **read** .
I think the good usage is using  `weed master` and `weed volume` as cluster.
