### ISSUE TITLE
what about this logo?

### ISSUE THREAD

**Issue by yanyiwu** [chrislusf/weed-fs#72]
![image](http://img.ui.cn/data/file/2/9/7/180792.png)

My girlfriend made it. 
Maybe it can be used as this project's logo if you like it?

**Comment by chrislusf** [comment]
Thanks! Nice and cute!. Much healthier than weed. :) Where to put it?

**Comment by aszxqw** [comment]
Anywhere you like. e.g. README.md

**Comment by shel3over** [comment]
the project need some marketing :heart_eyes:

**Comment by chrislusf** [comment]
I feel we need a wikipedia page... anyone?

**Comment by shel3over** [comment]
@chrislusf  :+1:  
and anything that can help a newbie 
nice tutorial / updated doc / block / use cases / who is using it on production ....

**Comment by carmark** [comment]
Maybe it will be better to create a website to hold the whole documents, introduce, tutorial, and so on.

The official website will be more easy to understand than github.

**Comment by misiek08** [comment]
We need to rewrite GoogleCode wiki to github's one.

**Comment by chrislusf** [comment]
Added to README
