### ISSUE TITLE
single point of failure

### ISSUE THREAD

**Issue by aszxqw** [chrislusf/weed-fs#74]
3 master server: mA mB mC
2 volume server: vA vB

mA is the leader of (mA,mB,mC) cluster.
and  vA and vB are connected with mA; (replication is "001")

If mA is down, mB become the leader of (mB,mC) as my expectation.
But why don't vA and vB is still looking up for mA when writing replication?
When vA and vB will realize to looking up for mB for writing replication?

In this case, when mA is down and then I submit file to mB;
it always returns e.g. `{"error":"Failed to write to replicas for volume 3"}`

How to solve this problem about SPOF?

**Comment by chrislusf** [comment]
Fixed with change 0e23ee4dce0f700f1aa0651bcce551336f428c85

**Comment by chrislusf** [comment]
https://github.com/chrislusf/weed-fs/commit/0e23ee4dce0f700f1aa0651bcce551336f428c85#diff-55856aeec83c67cc06ecc09eef9976c0

**Comment by aszxqw** [comment]
Thanks!
But is it safe for concurrent access?

**Comment by aszxqw** [comment]
If not, maybe this pr(https://github.com/chrislusf/weed-fs/pull/75) can help.
