### ISSUE TITLE
Should I delete  the no use file？

### ISSUE THREAD

**Issue by daixiaogang** [chrislusf/weed-fs#751]
Thanks for your great job! I am a newbee for using your fiesystem,but I find it is awesome！When I use it, I meet soem problem, If I delete the file that no use , when I upload the same file,the system may occour "use of closed file",what is the reason?

**Comment by chrislusf** [comment]
Please follow the issue template and fill in the commands you used.

**Comment by daixiaogang** [comment]
作者大大，是这样的，不知道是不是我改了绑定的IP地址，但是卷目录没有变，或者是我删除了文件，我删除文件用的java客户端，但是我看weed命令里貌似没有删除选项。现在的问题是文件系统(win10)会报错：”failed to read file size data/t_v1/3.dat”:use of closed file"
