### ISSUE TITLE
How to migrate volume from server `A` to `B`?

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/weed-fs#77]
Suppose we've got 3 volume servers (`A`, `B`, `C`) with `001` replication type. We wan't to remove volume server `C`. We have to migrate all volumes located on volume server `C` to `A` and `B`.

Is it possible to migrate volume with id `X` from server `A` to server `B`?

**Comment by aszxqw** [comment]
It is ok.
```
md5 vol1/1.dat vol2/1.dat
MD5 (vol1/1.dat) = c1a49a0ee550b44fef9f8ae9e55215c7
MD5 (vol2/1.dat) = c1a49a0ee550b44fef9f8ae9e55215c7
md5 vol1/1.idx vol2/1.idx
MD5 (vol1/1.idx) = b9edc95795dfb3b0f9063c9cc9ba8095
MD5 (vol2/1.idx) = b9edc95795dfb3b0f9063c9cc9ba8095
```
if the name(1.dat) of volume is the same, and the file will be the same.  so it is ok to move them.
when volume server is starting, it will read all the (*.dat, *.idx) of its dir , and take control of their read and write.

So if you move one volume from one volumeserver(A) to another volumeserver(B)  ,  and A will lost control of the volume, and B will take control of the volume.

But you should remember to stop the servers before moving.

**Comment by fedotxxl** [comment]
Got it. Thank you. Can you add this case to http://weed-fs.readthedocs.org/en/latest/usecases.html ?

**Comment by aszxqw** [comment]
@fedotxxl  https://github.com/chrislusf/weed-fs/pull/78/files
