### ISSUE TITLE
weed listen ip on 0.0.0.0 ,regardless of -ip= setting

### ISSUE THREAD

**Issue by wu0407** [chrislusf/weed-fs#81]
this is a bug ? find in 0.67-0.68 version

[root@backgroup ~]# ps aux | grep weed
root     15526  0.0  0.0 103252   840 pts/0    R+   17:23   0:00 grep weed
weedfs   32554  0.0  0.0 777940 24076 ?        Sl    2014  21:58 /usr/local/weed/weed master -mdir=/opt/weedfs -ip=10.168.241.178
[root@backgroup ~]# netstat -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name   
tcp        0      0 0.0.0.0:6379                0.0.0.0:*                   LISTEN      11159/redis-server  
tcp        0      0 0.0.0.0:11211               0.0.0.0:*                   LISTEN      4755/memcached      
tcp        0      0 0.0.0.0:4369                0.0.0.0:*                   LISTEN      4621/epmd           
tcp        0      0 0.0.0.0:9333                0.0.0.0:*                   LISTEN      32554/weed

**Comment by chrislusf** [comment]
This is expected. By default the listen ip address is 0.0.0.0. If you need to change it, use "-ip.bind" option.
