### ISSUE TITLE
get content type error

### ISSUE THREAD

**Issue by xinqiyang** [chrislusf/weed-fs#82]
hi,

I use weed-fs 1 years ago.  It is an old version [0.45] of weed.  
I post an image to weedfs, then I get it from browser ,  It will display correctly. 

curl -F file=@/home/chris/myphoto.jpg http://localhost:9333/submit

when I use 0.67 of weed.  I do the same post, But the same images cannot  display in the browser correctly.  It cannot display then do download in the chrome.  

what is wrong about the weed version up?  How can I config to this  get header output ? 

please help me.

**Comment by chrislusf** [comment]
I cannot reproduce this case. Please show me the commands you actually used.
