### ISSUE TITLE
Master and Volume don't see each other.

### ISSUE THREAD

**Issue by oracle1wr** [chrislusf/weed-fs#83]
I tried to run a new version (0.68) on openstack and it doesn't work. Servers don't see each other. No logs, it looks like the volume doesn't even try to join master. Here are the run instructions I used. BTW 0.45 version works.  

$OPENSHIFT_REPO_DIR/diy/weed volume -max=100 -ip=$OPENSHIFT_DIY_IP -port=$OPENSHIFT_DIY_PORT -ip.bind=$OPENSHIFT_DIY_IP -mserver=storage-master.domain.com:80 -publicIp="storage-volume02.domain.com:80"  -dir="$OPENSHIFT_DATA_DIR" > $OPENSHIFT_DIY_DIR/logs/volume.log 2>&1 &

$OPENSHIFT_REPO_DIR/diy/weed master -mdir="$OPENSHIFT_DATA_DIR" -port=8080 -ip=$OPENSHIFT_DIY_IP -ip.bind=$OPENSHIFT_DIY_IP  > $OPENSHIFT_DIY_DIR/logs/master.log 2>&1 &

**Comment by chrislusf** [comment]
Your master is on 8080 and volume server is using port 80?

**Comment by oracle1wr** [comment]
8080 is only port that is avaliable inside the server, it is mapped to 80. So from outside the port is 80, from inside it is 8080. For example if you have tomcat that is binded to 8080 port, you can make a call to the tomcat from outside only throug port 80.

**Comment by oracle1wr** [comment]
The same configuration works for 0.45, here is a config:
$OPENSHIFT_REPO_DIR/diy/weed volume -max=100 -ip=$OPENSHIFT_DIY_IP -port=8080 -mserver=storage-master.domain.com:80 -publicUrl="storage-volume01.domain.com:80"  -dir="$OPENSHIFT_DATA_DIR" -debug=true > $OPENSHIFT_DIY_DIR/logs/volume.log 2>&1 &

$OPENSHIFT_REPO_DIR/diy/weed master -mdir="$OPENSHIFT_DATA_DIR" -port=8080 -ip=$OPENSHIFT_DIY_IP -debug=true > $OPENSHIFT_DIY_DIR/logs/master.log 2>&1 &

**Comment by chrislusf** [comment]
please use "weed -v=4 volume ..." to show more debugging message.

**Comment by oracle1wr** [comment]
Here are logs for master (0.68):

command:
$OPENSHIFT_REPO_DIR/diy/weed -v=4 -log_dir=$OPENSHIFT_DIY_DIR/logs/master.log  master -mdir="$OPENSHIFT_DATA_DIR" -port=8080 -ip=$OPENSHIFT_DIY_IP -ip.bind=$OPENSHIFT_DIY_IP &

logs:
I0211 19:27:16 15141 file_util.go:20] Folder /var/lib/openshift/54dbed6e4382ecf682000066/app-root/data/ Permission: -rwxr-x---
I0211 19:27:16 15141 topology.go:86] Using default configurations.
I0211 19:27:16 15141 master_server.go:58] Volume Size Limit is 30000 MB
I0211 19:27:16 15141 master.go:70] Start Seaweed Master 0.68 at 127.10.157.1:8080
I0211 19:27:16 15141 raft_server.go:50] Starting RaftServer with IP:127.10.157.1:8080:
[raft]19:27:16.426141 [127.10.157.1:8080 Term:0] readConf.open  /var/lib/openshift/54dbed6e4382ecf682000066/app-root/data/conf
[raft]19:27:16.426327 update.commit.index  1
[raft]19:27:16.426340 log.open.open  /var/lib/openshift/54dbed6e4382ecf682000066/app-root/data/log
[raft]19:27:16.426369 log.open.exist  /var/lib/openshift/54dbed6e4382ecf682000066/app-root/data/log
[raft]19:27:16.426485 [127.10.157.1:8080 Term:0] server.peer.add:  127.10.157.1:8080 0
[raft]19:27:16.433982 open.log.append log index  1
[raft]19:27:16.434026 open.log.append log index  2
[raft]19:27:16.434058 open.log.append log index  3
[raft]19:27:16.434076 open.log.append: finish 
[raft]19:27:16.434082 open.log.recovery number of log  3
[raft]19:27:16.434096 [127.10.157.1:8080 Term:1] start from previous saved state
[raft]19:27:16.434106 Name: 127.10.157.1:8080, State: follower, Term: 1, CommitedIndex: 1 
I0211 19:27:16 15141 raft_server.go:103] Old conf,log,snapshot should have been removed.
[raft]19:27:16.434300 [127.10.157.1:8080 Term:1] server.loop.run  follower
[raft]19:27:39.626590 [127.10.157.1:8080 Term:1] server.loop.run  candidate
[raft]19:27:39.626645 [127.10.157.1:8080 Term:2] server.candidate.recv.enough.votes
I0211 19:27:39 15141 master_server.go:86] [ 127.10.157.1:8080 ] 127.10.157.1:8080 becomes leader.
[raft]19:27:39.626677 [127.10.157.1:8080 Term:2] server.loop.run  leader
[raft]19:27:39.626683 [127.10.157.1:8080 Term:2] leaderLoop.set.PrevIndex to  3
[raft]19:27:39.626721 [127.10.157.1:8080 Term:2] server.command.process
[raft]19:27:39.626789 setCommitIndex.set.result index: 2, entries index: 1
[raft]19:27:39.626796 setCommitIndex.set.result index: 3, entries index: 2
[raft]19:27:39.626801 setCommitIndex.set.result index: 4, entries index: 3
[raft]19:27:39.626818 [127.10.157.1:8080 Term:2] commit index  4

**Comment by oracle1wr** [comment]
Here are logs for volume (0.68):

command:
$OPENSHIFT_REPO_DIR/diy/weed -v=4 -log_dir=$OPENSHIFT_DIY_DIR/logs/volume.log  volume -max=100 -ip=$OPENSHIFT_DIY_IP -port=$OPENSHIFT_DIY_PORT -ip.bind=$OPENSHIFT_DIY_IP -mserver=master-weed.rhcloud.com:80 -publicIp="master-weed.rhcloud.com:80" -dir="$OPENSHIFT_DATA_DIR"  &

logs:
I0211 19:24:56 48117 file_util.go:20] Folder /var/lib/openshift/54dbede1e0b8cd7881000042/app-root/data/ Permission: -rwxr-x---
I0211 19:24:56 48117 store.go:232] Store started on dir: /var/lib/openshift/54dbede1e0b8cd7881000042/app-root/data/ with 0 volumes max 100
I0211 19:24:56 48117 volume.go:94] Start Seaweed volume server 0.68 at 127.12.94.129:8080
I0211 19:24:56 48117 list_masters.go:18] list masters result :{"IsLeader":true,"Leader":"127.10.157.1:8080"}
I0211 19:24:56 48117 store.go:61] current master node is :127.10.157.1:8080
I0211 19:24:57 48117 volume_server.go:68] Volume Server Failed to talk with master: Post http://127.10.157.1:8080/dir/join: dial tcp 127.10.157.1:8080: no route to host
I0211 19:24:59 48117 volume_server.go:68] Volume Server Failed to talk with master: Post http://127.10.157.1:8080/dir/join: dial tcp 127.10.157.1:8080: no route to host
......

**Comment by oracle1wr** [comment]
volume tries to connect to 127.10.157.1:8080 but should go to master-weed.rhcloud.com:80.

I also tried to run master with ip=master-weed.rhcloud.com, but it fails on start.

like this:
$OPENSHIFT_REPO_DIR/diy/weed -v=4 -log_dir=$OPENSHIFT_DIY_DIR/logs/master.log  master -mdir="$OPENSHIFT_DATA_DIR" -port=8080 -ip=master-weed.rhcloud.com -ip.bind=$OPENSHIFT_DIY_IP &

it throws:
I0211 19:36:28 54042 file_util.go:20] Folder /var/lib/openshift/54dbed6e4382ecf682000066/app-root/data/ Permission: -rwxr-x---
I0211 19:36:28 54042 topology.go:86] Using default configurations.
I0211 19:36:28 54042 master_server.go:58] Volume Size Limit is 30000 MB
I0211 19:36:28 54042 master.go:70] Start Seaweed Master 0.68 at 127.10.157.1:8080
I0211 19:36:28 54042 raft_server.go:50] Starting RaftServer with IP:master-weed.rhcloud.com:8080:
[raft]19:36:28.343895 [master-weed.rhcloud.com:8080 Term:0] readConf.open  /var/lib/openshift/54dbed6e4382ecf682000066/app-root/data/conf
[raft]19:36:28.344017 update.commit.index  1
[raft]19:36:28.344026 log.open.open  /var/lib/openshift/54dbed6e4382ecf682000066/app-root/data/log
[raft]19:36:28.344045 log.open.exist  /var/lib/openshift/54dbed6e4382ecf682000066/app-root/data/log
[raft]19:36:28.344149 [master-weed.rhcloud.com:8080 Term:0] server.peer.add:  127.10.157.1:8080 0
[raft]19:36:28.348375 open.log.append log index  1
[raft]19:36:28.348401 open.log.append log index  2
[raft]19:36:28.348415 open.log.append log index  3
[raft]19:36:28.348429 open.log.append log index  4
[raft]19:36:28.348438 open.log.append: finish 
[raft]19:36:28.348442 open.log.recovery number of log  4
[raft]19:36:28.348452 [master-weed.rhcloud.com:8080 Term:2] start from previous saved state
[raft]19:36:28.348461 Name: master-weed.rhcloud.com:8080, State: follower, Term: 2, CommitedIndex: 1 
[raft]19:36:28.348504 [master-weed.rhcloud.com:8080 Term:2] server.loop.run  follower
I0211 19:36:28 54042 raft_server.go:103] Old conf,log,snapshot should have been removed.
[raft]19:36:58.538398 [master-weed.rhcloud.com:8080 Term:2] server.loop.run  candidate
[raft]19:36:58.538476 peer.vote:  master-weed.rhcloud.com:8080 -> 127.10.157.1:8080
[raft]19:36:58.538739 master-weed.rhcloud.com:8080 POST http://127.10.157.1:8080/cluster/requestVote
[raft]19:36:58.539686 master-weed.rhcloud.com:8080 RECV /requestVote
[raft]19:36:58.539729 [master-weed.rhcloud.com:8080 Term:3] server.rv.vote:  master-weed.rhcloud.com:8080  votes for master-weed.rhcloud.com:8080 at term 3
[raft]19:36:58.540041 peer.vote.recv:  master-weed.rhcloud.com:8080 <- 127.10.157.1:8080
[raft]19:36:58.540162 [master-weed.rhcloud.com:8080 Term:3] server.candidate.vote.granted:  1
[raft]19:36:58.540172 [master-weed.rhcloud.com:8080 Term:3] server.candidate.recv.enough.votes
I0211 19:36:58 54042 master_server.go:86] [ master-weed.rhcloud.com:8080 ] master-weed.rhcloud.com:8080 becomes leader.
[raft]19:36:58.540266 [master-weed.rhcloud.com:8080 Term:3] server.loop.run  leader
[raft]19:36:58.540273 [master-weed.rhcloud.com:8080 Term:3] leaderLoop.set.PrevIndex to  4
[raft]19:36:58.540295 peer.heartbeat:  127.10.157.1:8080 1s
[raft]19:36:58.540318 [master-weed.rhcloud.com:8080 Term:3] server.command.process
[raft]19:36:59.540472 peer.heartbeat.flush:  127.10.157.1:8080
[raft]19:36:59.540499 log.entriesAfter.partial:  4   0x82bbad0
[raft]19:36:59.540505 log.entriesAfter: startIndex: 0  length 5
[raft]19:36:59.540519 peer.append.send: master-weed.rhcloud.com:8080->127.10.157.1:8080 [prevLog:4 length: 1]
[raft]19:36:59.540574 master-weed.rhcloud.com:8080 POST http://127.10.157.1:8080/cluster/appendEntries
[raft]19:36:59.540754 master-weed.rhcloud.com:8080 RECV /appendEntries
[raft]19:36:59.540805 [master-weed.rhcloud.com:8080 Term:3] server.loop.end
panic: assertion failed: leader.elected.at.same.term.3

**Comment by chrislusf** [comment]
I checked in a fix in the master branch. https://github.com/chrislusf/weed-fs/commit/eff83a87d126faf0dd5b05876690271777f41e65

**Comment by oracle1wr** [comment]
Here is what I got with 0.69 beta.
command:
$OPENSHIFT_REPO_DIR/diy/weed master -publicUrl=master-weed.rhcloud.com:80 -mdir="$OPENSHIFT_DATA_DIR" -port=8080 -ip=$OPENSHIFT_DIY_IP -ip.bind=$OPENSHIFT_DIY_IP > $OPENSHIFT_DIY_DIR/logs/master.log 2>&1 &

I0212 02:15:48 09353 file_util.go:20] Folder /var/lib/openshift/54dbed6e4382ecf682000066/app-root/data/ Permission: -rwxr-x---
I0212 02:15:48 09353 topology.go:86] Using default configurations.
I0212 02:15:48 09353 master_server.go:59] Volume Size Limit is 30000 MB
I0212 02:15:48 09353 master.go:70] Start Seaweed Master 0.69 beta at 127.10.157.1:8080
I0212 02:15:48 09353 raft_server.go:103] Old conf,log,snapshot should have been removed.
I0212 02:16:10 09353 master_server.go:87] [ master-weed.rhcloud.com:80 ] master-weed.rhcloud.com:80 becomes leader.
panic: assertion failed: leader.elected.at.same.term.4

**Comment by chrislusf** [comment]
Please try it in an empty folder or remove previous "conf,log,snapshot" files or folders.

**Comment by oracle1wr** [comment]
Thank you Chris!
It looks good now. A master server was able to add a volume. I'll play with it a little and let you know if everything is good.

**Comment by oracle1wr** [comment]
0.69 is working. Only problem I experienced is java client. I fixed and everything else is working as expected. Let me know if you want a patch for the client.

One more question I have, it is related to multiple volumes. I have two, but only one is getting populated. Do you know what can be a reason?  Here is my master status json:

{
    "Topology": {
        "DataCenters": [
            {
                "Free": 193,
                "Id": "DefaultDataCenter",
                "Max": 200,
                "Racks": [
                    {
                        "DataNodes": [
                            {
                                "Free": 93,
                                "Max": 100,
                                "PublicUrl": "storage-volume01.izort.com:80",
                                "Url": "127.3.84.1:8080",
                                "Volumes": 7
                            },
                            {
                                "Free": 100,
                                "Max": 100,
                                "PublicUrl": "storage-volume02.izort.com:80",
                                "Url": "127.11.252.1:8080",
                                "Volumes": 0
                            }
                        ],
                        "Free": 193,
                        "Id": "DefaultRack",
                        "Max": 200
                    }
                ]
            }
        ],
        "Free": 193,
        "Max": 200,
        "layouts": [
            {
                "collection": "",
                "replication": "000",
                "ttl": "",
                "writables": [
                    7,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6
                ]
            }
        ]
    },
    "Version": "0.69 beta"
}

**Comment by chrislusf** [comment]
It's likely you started with one volume server, tested with submitting some files, and added another volume server. The first set of 7 volumes are assigned on the first first submission.

You can remove the volumes and start again.

Or you can allocate volumes directly with the http api
http://weed-fs.readthedocs.org/en/latest/api.html#pre-allocate-volumes

**Comment by oracle1wr** [comment]
This is what I'm getting when run: http://storage-master.domain.com/vol/grow?replication=000&count=7

{"error":"Failed to assign 9: Post http://127.11.252.1:8080/admin/assign_volume: dial tcp 127.11.252.1:8080: no route to host"}

**Comment by oracle1wr** [comment]
this command worker:
curl "http://$OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT/admin/assign_volume?replication=000&volume=9"

**Comment by chrislusf** [comment]
the master need to tell volume server to add some volumes. The error showed the master can not connect to volume server via 127.11.252.1:8080

**Comment by oracle1wr** [comment]
The only way master can connect to volume is through publicUrl. Ok, at least I can do it directly.

**Comment by oracle1wr** [comment]
one more minor issue. A volume server redirects to an internal IP when a volume number specified in a file hash is not exist in the volume server.

http://storage-volume02.domain.com/4,0310a2b916aaec - volume №4 is siting on 01 volume server. This call redirects to: http://127.3.84.1:8080/4,0310a2b916aaec 
and expectedly can't connect to an internal ip.

**Comment by chrislusf** [comment]
Good point. Fixed now.
