### ISSUE TITLE
Losts of "volume_server_handlers.go:155] response write error" errors in our production server log files

### ISSUE THREAD

**Issue by yourchanges** [chrislusf/weed-fs#85]
Is this a problem? how could be happened? any suggestions?

Here is details(logs are on both two volume servers):

(master server internal ip : 10.252.130.159)

volume server 1 :(v0.68)

	I0211 18:50:06 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:46065: i/o timeout
	I0211 18:50:21 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:46137: i/o timeout
	I0211 18:50:37 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:46205: i/o timeout
	I0211 19:00:18 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:48455: i/o timeout
	I0211 19:00:54 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:48597: i/o timeout
	I0211 19:56:01 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:33519: connection reset by peer
	I0211 20:26:39 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:42285: connection reset by peer
	I0211 20:37:20 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:45272: connection reset by peer
	I0211 21:34:19 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:58623: connection reset by peer
	I0212 08:53:58 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:36510: connection reset by peer
	I0212 09:44:07 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:48289: connection reset by peer
	I0212 11:00:59 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:37052: connection reset by peer
	I0212 11:01:32 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:37280: connection reset by peer
	I0212 14:35:10 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:33136: broken pipe
	I0212 14:36:09 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:33423: broken pipe
	I0212 14:36:30 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:33530: connection reset by peer
	I0212 14:36:30 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:33532: connection reset by peer
	I0212 14:36:58 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:33629: connection reset by peer

	I0212 15:15:47 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:43678: connection reset by peer

	I0212 16:07:28 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:56089: connection reset by peer
	I0212 16:07:28 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:56084: connection reset by peer

	I0212 18:21:45 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:38085: broken pipe
	I0212 18:34:32 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:40850: broken pipe
	I0212 18:35:39 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:41118: connection reset by peer

	I0212 21:13:23 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:53229: connection reset by peer

	I0212 21:51:14 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:33695: connection reset by peer
	I0212 21:51:14 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:33701: broken pipe

	I0212 21:53:17 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:34297: broken pipe
	I0212 21:54:11 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:34514: connection reset by peer

	I0212 22:00:14 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:36014: broken pipe
	I0212 22:05:46 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:37219: connection reset by peer

	I0212 22:18:07 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:40511: broken pipe
	I0213 14:20:49 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:32919: connection reset by peer

	I0213 14:23:39 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:34039: broken pipe
	I0213 14:23:39 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:34037: broken pipe

	I0213 14:45:19 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:48873: broken pipe

	I0213 14:51:17 21828 volume_server_handlers.go:196] response write error: write tcp 10.252.130.159:50847: i/o timeout
	I0213 14:51:17 21828 volume_server_handlers.go:196] response write error: write tcp 10.252.130.159:50845: i/o timeout

	I0213 15:09:31 21828 volume_server_handlers.go:155] response write error: write tcp 10.252.130.159:55504: connection reset by peer

**Comment by chrislusf** [comment]
How busy is your traffic?

**Comment by yourchanges** [comment]
Almost not busy at all

**Comment by chrislusf** [comment]
The timeout is on the connection with haproxy or master server?
The error happens for what percent of the total traffic?

**Comment by yourchanges** [comment]
Here is the 

## Deploy structure

	10.252.130.159:9333(master)		--->  			10.252.130.159:5088(haproxy)
																																	 /                                            \   
																								10.252.133.22:5083 (volume1)               10.252.135.207:5084(volume2)  

			Replication Stratage: 001

So, it's always get the content via haproxy from volume server.

And there are lots of request from mobile side with a bad network.

**Comment by chrislusf** [comment]
this makes sense. the clients are dropping connections. the filesystem is doing the right thing.
