### ISSUE TITLE
how to build weed-fs binaries

### ISSUE THREAD

**Issue by cglewis** [chrislusf/weed-fs#86]
I'd like to build the latest from master, but not sure of a simple way to do that.

I had hoped I could do something like this (in the docker registry [here](https://registry.hub.docker.com/u/library/golang/)):

```
git clone https://github.com/chrislusf/weed-fs.git
cd weed-fs
docker run --rm -it -v "$PWD":/usr/src/weed -w /usr/src/weed golang:1.4.1-cross bash
$ for GOOS in darwin linux; do
>   for GOARCH in 386 amd64; do
>     go build -v -o myapp-$GOOS-$GOARCH
>   done
> done
```

But it fails I think due to the directory structure of the Go files for this project.  Any guidance on how to build my own binaries from master would be greatly appreciated!

**Comment by chrislusf** [comment]
I am using goxc
