### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by joras** [chrislusf/weed-fs#88]
I installed the darwin 0.68 binary and on assign i get following error in the logs.

I0220 11:41:19 97016 volume_growth.go:206] Failed to assign 7 to [NodeImpl:topo:DefaultDataCenter:DefaultRack:127.0.0.1:8080 ,volumes:map[], Ip:127.0.0.1, Port:8080, PublicUrl:localhost:8080, Dead:false] error invalid character '<' looking for beginning of value

**Comment by chrislusf** [comment]
There are some error on the volume server side. It's not responding JSON for http://127.0.0.1/admin/assign_volume?volume=7

But I will need more info to tell more.

**Comment by joras** [comment]
It's a clean install, thus is really hard to add additional info because I just installed it, ran it with 'weed server' command, and tried to call assign. Later I tried running masters and volumes separately also, that made no difference.

**Comment by chrislusf** [comment]
What do you see when pasting the irk to the browser?

**Comment by joras** [comment]
My apologies, I had nginx running at the same port(8080). It is weird though that weed volume did was able to listen to the same port? Or is the error hidden?

**Comment by chrislusf** [comment]
This could be similar to this http://stackoverflow.com/questions/24483955/go-listen-on-port-which-is-already-in-use-not-returning-error

The error did not happen because weedfs volume by default is listening on ":8080".
