### ISSUE TITLE
my /dir/assign response is always localhost:8080

### ISSUE THREAD

**Issue by breaklee** [chrislusf/weed-fs#89]
how can i correct public server ip to setup?

my master setup : ./weed master &
my weed slave setup : ./weed  volume -dir=/home/ubuntu/data -max=10 -mserver="public ip here" -port=8080

"public ip here" => my public server ip

but my /dir/assign infomation is always localhost:8080

**Comment by chrislusf** [comment]
Start volume server this way:

weed volume -ip=127.0.0.1 -publicUrl="xxx.com" -mserver="..."

curl http://localhost:9333/dir/assign
{"fid":"16,015fce92a2","url":"127.0.0.1:8080","publicUrl":"xxx.com","count":1}

**Comment by breaklee** [comment]
@chrislusf   thanks!
