### ISSUE TITLE
Public port & url

### ISSUE THREAD

**Issue by ernado** [chrislusf/weed-fs#9]
Use case:
I have a weed servers:
```
s1.hostname.com:8080
s2.hostname.com:8080
```
I can place them behind reverse-proxy (nginx), and they will be accessible as
```
hostname.com/media/s1/:80
hostname.com/media/s2/:80
```
or even
```
hostname.com/media:80
```
or even
```
hostname.com/media:443
```
Which is
```
http://hostname.com/media
https://hostname.com/media
```
In case of 100 replication enabled on master server.

Now i can achieve this only with manual rewrite rules for s1 and s2.

It could be like
```
weed volume -port 8080 -publicPort 80 -publicPort 443 -publicURL "hostname.com/media"
```
Or something like this

**Comment by chrislusf** [comment]
I will take back my previous comments. The publicURL will become a more free style customizable URL. New versions will support it. But not yet.

**Comment by yourchanges** [comment]
Wanted too.

**Comment by yourchanges** [comment]
see #76

**Comment by chrislusf** [comment]
Fixed in https://github.com/chrislusf/weed-fs/commit/cc724305b665bb13a592334cf4739c4498df9d72

This way, the publicUrl becomes free style text. You can use -publicUrl="hostname.com/media:433_or_any_text".

**Comment by chrislusf** [comment]
FYI: That commit is not complete. I added one more commit to make it work.
