### ISSUE TITLE
i uploaded tar.gz file but when i downloaded this file, size is different

### ISSUE THREAD

**Issue by breaklee** [chrislusf/weed-fs#90]
i uploaded tar.gz file but when i downloaded this file, size is different
maybe i think this files is untar.

**Comment by chrislusf** [comment]
fixed with commit 9a1cdf791b3e73cd0b382c4831b6b2d20b2f06f1

**Comment by breaklee** [comment]
thanks :)

**Comment by breaklee** [comment]
i'm a just end user i'm not go lang and comple. how can i download fixed version?
could you upload fixed binaries for all? 
thanks! @chrislusf

**Comment by chrislusf** [comment]
I uploaded 0.69beta version to https://bintray.com/chrislusf/Weed-FS/seaweed/view

**Comment by breaklee** [comment]
@chrislusf  thanks!!  i have to learn GO lang :)
