### ISSUE TITLE
Add option to store needle index in leveldb

### ISSUE THREAD

**Issue by chrislusf** [chrislusf/weed-fs#99]
Currently 1 million files takes about 24MB memory.

The memory consumption could be high if storing too many files, e.g. 6000million small files.

**Comment by h-sen-dev** [comment]
+1
and please keep project independent from no-golang libs. so goleveldb can be helpful.

**Comment by yourchanges** [comment]
+1

**Comment by faaliyet** [comment]
why not boltdb? read performance much better !

**Comment by chrislusf** [comment]
Added leveldb and boltdb support.

boltdb is fairly slow to write, about 6 minutes for recreating index for 1553934 files. Boltdb loads 1,553,934 x 16 = 24,862,944bytes from disk, and generate the boltdb as large as 134,217,728 bytes in 6 minutes.
To compare, for leveldb, it recreates index in leveldb as large as 27,188,148 bytes in 8 seconds.

To test the memory consumption, the leveldb or boltdb index are created. There are 7 volumes in benchmark collection, each with about 1553K files. The server is restarted, hen I start the benchmark tool to read lots of files.
For leveldb, the memory starts at 142,884KB, and stays at 179,340KB.
For boltdb, the memory starts at 73,756KB, and stays at 144,564KB.
For in-memory, the memory starts at 368,152KB, and stays at 448,032KB.

To test the write speed, I use the benchmark tool with default parameters.
For boltdb, the write is about 4.1MB/s, 4.1K files/s
For leveldb, the writes is about 10.4MB/s, 10.4K files/s
For in-memory, it is a tiny bit faster, not statistically different.

**Comment by faaliyet** [comment]
any results for read speeds ? just wonder the read performance "boltdb vs leveldb".

btw, thanks for the research.

**Comment by chrislusf** [comment]
Read speeds are about the same.

**Comment by xiaoweihong** [comment]
-index string
    	Choose [memory|leveldb|leveldbMedium|leveldbLarge] mode for memory~performance balance. (default "memory")
i confuse about "leveldb|leveldbMedium|leveldbLarge",how different

**Comment by chrislusf** [comment]
more memory usage for better performance
